##
## EPITECH PROJECT, 2020
## 302separation
## File description:
## Makefile
##

all:
	@cp 302separation.py 302separation
	@chmod +x 302separation

clean:

fclean: clean
	@rm 302separation

test: re
	@./test/test.sh

re: fclean all