##
## EPITECH PROJECT, 2020
## groundhog
## File description:
## Makefile
##

all:
	@cp 301dannon.py 301dannon
	@chmod +x 301dannon

clean:

fclean: clean
	@rm 301dannon

test: re
	@./test/test.sh

re: fclean all