##
## EPITECH PROJECT, 2020
## 304pacman
## File description:
## Makefile
##

all:
	@cp 304pacman.py 304pacman
	@chmod +x 304pacman

clean:

fclean: clean
	@rm 304pacman

test: all
	@./test/test.sh

re: fclean all