##
## EPITECH PROJECT, 2020
## 303make
## File description:
## Makefile
##

all:
	@cp 303make.py 303make
	@chmod +x 303make

clean:

fclean: clean
	@rm 303make

test: all
	@./test/test.sh

re: fclean all